import re

IT = r"_[^_]+_"
LANG = r"(L|OE|OFr|ONFr|ON|AFr|MLG|ME|Mn.E|MDu|Med.L|Du|G|OIcel|LG|Anglo-L|OFris)\."
CAP_WORD = r"[A-ZÞ]([a-zþȝ]|p\(p\))+(\([en]\))?"
GRM = r"(prep|n|v|adj|adv|pl|fem|str|wk|neut|dat|acc|gen|sg|compar\. adv|nom|pa|t|3 sg|conj|intr|compar)\."
SUP = r"\^\d+"
QV = r"_q\.v\._"
NED = r"_N\.E\.D\._"
GLOSS = r"[a-z ']+"
ETC = r"&c\."
INFL_BY = r"infl\. by"

GRMS = fr"{GRM}( {GRM})*"

regexes = [
    re.compile(r)
    for r in [
        fr"_See_ next\.$",
        fr"{CAP_WORD} \+ {CAP_WORD}, _{GRM}_{SUP}$",
        fr"{CAP_WORD} \+ {CAP_WORD}, _{GRM}_$",
        fr"{CAP_WORD} \+ {CAP_WORD}, {QV}$",
        fr"{CAP_WORD}- \+ {CAP_WORD}, _{GRM}_{SUP}$",
        fr"{CAP_WORD}- \+ {CAP_WORD}, {QV}$",
        fr"{CAP_WORD}, _{GRM}_ \+ {CAP_WORD}, {QV}$",
        fr"{CAP_WORD}, _{GRM}_ \+ {CAP_WORD}\.$",
        fr"{CAP_WORD}, {CAP_WORD} {INFL_BY} {CAP_WORD}\.$",
        fr"{CAP_WORD}, {CAP_WORD} \+ {CAP_WORD}, {QV}$",
        fr"{IT} \+ {LANG} {IT}, {GLOSS}\.$",
        fr"{IT} \+ {LANG} {IT}, {IT}\.$",
        fr"{IT} \+ {LANG} {IT}\.$",
        fr"{LANG} {IT} {GLOSS}\.$",
        fr"{LANG} {IT} {GRM}, {GLOSS}\.$",
        fr"{LANG} {IT} {GRMS}$",
        fr"{LANG} {IT} \({IT}, {GRM}\); {IT}\.$",
        fr"{LANG} {IT} \({IT}\) \+ {LANG} {IT}\.$",
        fr"{LANG} {IT} \({IT}\)\.$",
        fr"{LANG} {IT} \(in Sweet\)\.$",
        fr"{LANG} {IT} \(late {IT}\), {ETC}$",
        fr"{LANG} {IT} \(once\), {IT}\.$",
        fr"{LANG} {IT} \(or {IT}\) {IT}\.$",
        fr"{LANG} {IT} \+ {CAP_WORD}, {QV}$",
        fr"{LANG} {IT} \+ {CAP_WORD}\.$",
        fr"{LANG} {IT} \+ {GRM} {IT}\.$",
        fr"{LANG} {IT} \+ {IT} \(_see_ {CAP_WORD}\)\.$",
        fr"{LANG} {IT} \+ {IT} \(intensive\)\.$",
        fr"{LANG} {IT} \+ {IT} indef\.$",
        fr"{LANG} {IT} \+ {IT}, {GRMS}$",
        fr"{LANG} {IT} \+ {IT}, pp\. of {IT}\.$",
        fr"{LANG} {IT} \+ {IT}, pp\.$",
        fr"{LANG} {IT} \+ {IT}; cf\. {IT}\.$",
        fr"{LANG} {IT} \+ {IT}; cf\. prec\.$",
        fr"{LANG} {IT} \+ {IT}\.$",
        fr"{LANG} {IT} \+ {LANG} {IT}\.$",
        fr"{LANG} {IT} \+ \? {IT} \? {IT}\.$",
        fr"{LANG} {IT} and {IT}\.$",
        fr"{LANG} {IT} and {LANG} {IT}\.$",
        fr"{LANG} {IT} blended with {IT} \({IT}\)\.$",
        fr"{LANG} {IT} from {LANG} {IT}\.$",
        fr"{LANG} {IT} infl\. by {IT}, {GRM}$",
        fr"{LANG} {IT} or {IT}, infl\. by next\.$",
        fr"{LANG} {IT} rel\. to {IT}\.$",
        fr"{LANG} {IT} through {LANG}$",
        fr"{LANG} {IT}, {CAP_WORD}\.$",
        fr"{LANG} {IT}, {ETC}, {GLOSS}\.$",
        fr"{LANG} {IT}, {GLOSS} \(sound\)\.$",
        fr"{LANG} {IT}, {GLOSS} \+ {LANG} {IT}\.$",
        fr"{LANG} {IT}, {GLOSS}, {GLOSS}\.$",
        fr"{LANG} {IT}, {GLOSS}, \(in verse\) {GLOSS}\.$",
        fr"{LANG} {IT}, {GLOSS}, from {LANG} {IT}\.$",
        fr"{LANG} {IT}, {GLOSS}; _cf\._ {CAP_WORD}\.$",
        fr"{LANG} {IT}, {GLOSS}; {GRMS} {IT}\.$",
        fr"{LANG} {IT}, {GLOSS}; {IT}, {GLOSS}\.$",
        fr"{LANG} {IT}, {GLOSS}; cf\. {LANG} {IT}\.$",
        fr"{LANG} {IT}, {GLOSS}\.$",
        fr"{LANG} {IT}, {GLOSS}\.$",  # inconsistent comma?
        fr"{LANG} {IT}, {GRM} \+ {IT}\.$",
        fr"{LANG} {IT}, {GRM} and {GRM}; {IT}, {GRM}$",
        fr"{LANG} {IT}, {GRM} and {GRM}$",
        fr"{LANG} {IT}, {GRM} of {IT}\.$",
        fr"{LANG} {IT}, {GRM}, {GRM}; {IT}, {GRM}$",
        fr"{LANG} {IT}, {GRM}, {IT}, {GRM}$",
        fr"{LANG} {IT}, {GRM}, and {IT}, {GRM}$",
        fr"{LANG} {IT}, {GRM}; {IT}\.$",
        fr"{LANG} {IT}, {GRM}$",
        fr"{LANG} {IT}, {GRMS} {IT}\.$",
        fr"{LANG} {IT}, {GRMS}$",  # inconsistent comma?
        fr"{LANG} {IT}, {INFL_BY} {IT}\.$",
        fr"{LANG} {IT}, {INFL_BY} next\.$",
        fr"{LANG} {IT}, {INFL_BY} prec\.$",
        fr"{LANG} {IT}, {IT} \({GRM}\), {IT}\.$",
        fr"{LANG} {IT}, {IT} \(fem\.\)\.$",
        fr"{LANG} {IT}, {IT} \+ {GRM} {IT}\.$",
        fr"{LANG} {IT}, {IT} \+ {IT}\.$",
        fr"{LANG} {IT}, {IT}, {ETC}, {GRM}$",
        fr"{LANG} {IT}, {IT}, {ETC}$",
        fr"{LANG} {IT}, {IT}, {GLOSS}, {GLOSS}\.$",
        fr"{LANG} {IT}, {IT}, {GLOSS}\.$",
        fr"{LANG} {IT}, {IT}, {GRM}{SUP}$",
        fr"{LANG} {IT}, {IT}, {IT}, {ETC}$",
        fr"{LANG} {IT}, {IT}, {IT}\.$",
        fr"{LANG} {IT}, {IT}, str\. and wk\.$",
        fr"{LANG} {IT}, {IT}, str\., later wk\.$",
        fr"{LANG} {IT}, {IT}; {IT}; {IT}\.$",
        fr"{LANG} {IT}, {IT}; {IT}\.$",
        fr"{LANG} {IT}, {IT}; {LANG} {IT}\.$",
        fr"{LANG} {IT}, {IT}; pp\. {IT}\.$",
        fr"{LANG} {IT}, {IT}\.$",
        fr"{LANG} {IT}, {LANG} {IT}, {GLOSS}\.$",
        fr"{LANG} {IT}, {LANG} {IT}, {GRM}$",
        fr"{LANG} {IT}, {LANG} {IT}\.$",
        fr"{LANG} {IT}, \? {INFL_BY} {IT}, {ETC}",
        fr"{LANG} {IT}, \? {INFL_BY} {IT}\.$",
        fr"{LANG} {IT}, \? {IT}\.$",
        fr"{LANG} {IT}, \({GRMS}\) {GLOSS}\.$",
        fr"{LANG} {IT}, \(late\) {IT}\.$",
        fr"{LANG} {IT}, \(once in gloss\.\) {IT}\.$",
        fr"{LANG} {IT}, \(once\) {IT}\.$",
        fr"{LANG} {IT}, and {IT} prefix\.$",
        fr"{LANG} {IT}, cf\. {IT}\.$",
        fr"{LANG} {IT}, earlier {IT}\.$",
        fr"{LANG} {IT}, from {CAP_WORD}, {QV}$",
        fr"{LANG} {IT}, from {IT}, {GLOSS}\.$",
        fr"{LANG} {IT}, from {LANG} {IT}\.$",
        fr"{LANG} {IT}, from {LANG}$",
        fr"{LANG} {IT}, infl\. by {CAP_WORD}\.$",
        fr"{LANG} {IT}, influenced by {IT}\.$",
        fr"{LANG} {IT}, late {GRMS} {IT}\.$",
        fr"{LANG} {IT}, late {IT}\.$",
        fr"{LANG} {IT}, later {IT}\.$",
        fr"{LANG} {IT}, older {IT}\.$",
        fr"{LANG} {IT}, older, {IT}\.$",
        fr"{LANG} {IT}, or {IT}\.$",
        fr"{LANG} {IT}, or {LANG} {IT}, {IT}\.$",
        fr"{LANG} {IT}, orig\. 'mated' in chess\.$",
        fr"{LANG} {IT}, pers\. and impers\.$",
        fr"{LANG} {IT}, pp\. {IT}\.$",
        fr"{LANG} {IT}, pp\. {IT}$",  # @@@ missing final .
        fr"{LANG} {IT}, pp\., {GLOSS}\.$",
        fr"{LANG} {IT}, reduced under wk\. stress\.$",
        fr"{LANG} {IT}, rel\. to {CAP_WORD}, _{GRM}_{SUP}$",
        fr"{LANG} {IT}, rel\. to {CAP_WORD}, _{GRM}_$",
        fr"{LANG} {IT}, rel\. to {IT}, {GLOSS}\.$",
        fr"{LANG} {IT}, stem of {IT}\.$",
        fr"{LANG} {IT}, with {IT} > {IT}\.$",
        fr"{LANG} {IT}, with {LANG} {IT} > {IT}\.$",
        fr"{LANG} {IT}; _cf\._ next\.$",
        fr"{LANG} {IT}; _see_ {CAP_WORD}\.$",
        fr"{LANG} {IT}; _see_ next\.$",
        fr"{LANG} {IT}; _see_ prec\.$",
        fr"{LANG} {IT}; {GRM} {IT}, {IT}\.$",
        fr"{LANG} {IT}; {GRMS} {IT}, {IT}\.$",
        fr"{LANG} {IT}; {GRMS} {IT}\.$",
        fr"{LANG} {IT}; {IT} = {IT} \(see the rimes\)\.$",
        fr"{LANG} {IT}; {IT}, _{GRM}_$",
        fr"{LANG} {IT}; {IT}, {GRM}$",
        fr"{LANG} {IT}; {IT}, {IT} {GRM}$",
        fr"{LANG} {IT}; {IT}, {IT}\.$",
        fr"{LANG} {IT}; {IT}, pp\.$",
        fr"{LANG} {IT}; {IT}\.$",
        fr"{LANG} {IT}; {LANG} {IT}, {GRM}$",
        fr"{LANG} {IT}; {LANG} {IT}\.$",
        fr"{LANG} {IT}; {LANG}, {LANG} {IT}\.$",
        fr"{LANG} {IT}; \? {INFL_BY} {IT}\.$",
        fr"{LANG} {IT}; but see {NED}$",
        fr"{LANG} {IT}; cf\. {CAP_WORD}, _{GRM}_{SUP}$",
        fr"{LANG} {IT}; cf\. {IT}\.$",
        fr"{LANG} {IT}; cf\. {LANG} {IT}\.$",
        fr"{LANG} {IT}; cf\. next\.$",
        fr"{LANG} {IT}; early {LANG} {IT}\.$",
        fr"{LANG} {IT}; obscure\.$",
        fr"{LANG} {IT}; on the vowel _see_ {CAP_WORD}\.$",
        fr"{LANG} {IT}; see {NED}, s\.v\. _{CAP_WORD}_\.$",
        fr"{LANG} {IT}; see {NED}$",
        fr"{LANG} {IT}; see next\.$",
        fr"{LANG} {IT}; see note\.$",
        fr"{LANG} {IT}; see prec\.$",
        fr"{LANG} {IT}{SUP} \+ {IT}\.$",
        fr"{LANG} {IT}\. \(cf\. {LANG} {IT}\)\.$",
        fr"{LANG} {IT}\.{SUP}$",
        fr"{LANG} {IT}\.$",
        fr"{LANG} \? {IT}, rel\. to {IT}\.$",
        fr"{LANG} \? {IT}; {LANG} {IT}\.$",
        fr"{LANG} \(allit\.\) {IT}, {GLOSS}\.$",
        fr"{LANG} \(from {LANG}\) {IT}\.$",
        fr"{LANG} \(i\) {IT}, \(ii\) {IT}\.$",
        fr"{LANG} \(rare\) {IT}\.$",
        fr"{LANG} forms point to {LANG} {IT}\.$",
        fr"{LANG} in {IT}, {IT}\.$",
        fr"{LANG} in {IT}\.$",
        fr"{LANG}, {LANG} {IT}, {LANG} {IT}\.$",
        fr"{LANG}, {LANG} {IT}\.$",
        fr"{LANG}$",
        fr"\? {LANG} {IT} \(cf\. {IT}\)\.$",
        fr"\? {LANG} {IT}, {GLOSS}; _cf\._ {CAP_WORD}\.$",
        fr"\? {LANG} {IT}, {IT}, {GLOSS}\.$",
        fr"\? {LANG} {IT}; see {NED}$",
        fr"\? {LANG} {IT}\.$",
        fr"\? Altered form of {LANG} {IT}\.$",
        fr"\? Cf\. {LANG} {IT}, {GLOSS}\.$",
        fr"\? From next\.$",
        fr"\? From prec\.$",
        fr"\? Rel\. to next\.$",
        fr"\? Related to {CAP_WORD}, _{GRM}_{SUP}$",
        fr"\? Related to {CAP_WORD}, _{GRM}_$",
        fr"\? Same as next\.$",
        fr"A Northern form\. ON\. {IT}\.$",
        fr"As next\.$",
        fr"As prec\.$",
        fr"Back-formation from {CAP_WORD}\.$",
        fr"Cf\. {LANG} _[^_]+!_$",
        fr"Cf\. {LANG} {IT}, {GLOSS}\.$",
        fr"Cf\. {LANG} {IT}, {GRM}$",
        fr"Cf\. {LANG} {IT}, {IT}\.$",
        fr"Cf\. {LANG} {IT}, {LANG} {IT}\.$",  # , vs ;
        fr"Cf\. {LANG} {IT}; {LANG} {IT}\.$",  # , vs ;
        fr"Cf\. {LANG} {IT}; \? {LANG} {IT}\.$",
        fr"Cf\. {LANG} {IT}; see {NED}$",
        fr"Cf\. {LANG} {IT}.$",
        fr"Cf\. {LANG}, {LANG} {IT}, v\.$",
        fr"Cf\. {LANG}, {LANG}, {IT}\.$",
        fr"Cf\. MDu\., MLG\. {IT}\.$",
        fr"Children's language\.$",
        fr"Echoic, on model of next\.",
        fr"Echoic; _cf\._ {CAP_WORD}, {CAP_WORD}\.$",
        fr"Echoic; _cf\._ {CAP_WORD}\.$",
        fr"Echoic\.$",
        fr"Extended from {CAP_WORD} with abstract {IT}\.$",
        fr"Extended from {LANG} {IT}\.$",
        fr"Extended from prec\.$",
        fr"First two words of Latin prayer\.$",
        fr"Formed on {CAP_WORD} _{GRM}_$",  # inconsistenly missing commas
        fr"Formed on {CAP_WORD}, _{GRM}_$",
        fr"From _prec\._$",
        fr"From {CAP_WORD}, _{GRM}_; cf\. {LANG} {IT}\.$",
        fr"From {CAP_WORD}, _{GRM}_{SUP}$",
        fr"From {CAP_WORD}, _{GRM}_$",
        fr"From {CAP_WORD}, {CAP_WORD}\.$",
        fr"From {CAP_WORD}, {QV}$",
        fr"From {CAP_WORD}\.$",
        fr"From {IT}\.$",
        fr"From {LANG} {IT} \+ {IT}\.$",
        fr"From {LANG} {IT}, {GLOSS}; obscure\.$",
        fr"From {LANG} {IT}, {GLOSS}\.$",  # inconsistent comma?
        fr"From {LANG} {IT}, {GRM}$",
        fr"From {LANG} {IT}, {IT}, {GRM}$",
        fr"From {LANG} {IT}, {IT}, pp\.$",
        fr"From {LANG} {IT}, {IT}\.$",
        fr"From {LANG} {IT}, {LANG} {IT}, {GLOSS}\.$",
        fr"From {LANG} {IT}, {LANG} {IT}\.$",
        fr"From {LANG} {IT}\.$",
        fr"From {LANG}, {LANG} {IT}, {GRM}$",
        fr"From {LANG}, {LANG} {IT}\.$",
        fr"From next; cf, {LANG} {IT}\.$",  # @@@
        fr"From next\.$",
        fr"From pp\. of {CAP_WORD}, {QV}$",
        fr"From prec\. \(i\)\.$",
        fr"From prec\. in {LANG} sense '{GLOSS}'\.$",
        fr"From prec\.; {LANG} {IT}\.$",
        fr"From prec\.; cf\. {LANG} {IT}, {GRM}$",
        fr"From prec\.; cf\. {LANG} {IT}\.$",
        fr"From prec\.$",
        fr"From pres\. p\. of {CAP_WORD}\.$",
        fr"From stem of {CAP_WORD}; cf\. {LANG} {IT}\.$",
        fr"Further reduced from {CAP_WORD}, {QV}$",
        fr"Late {LANG} {IT}, from {LANG} {IT}\.$",
        fr"Late OE\. {IT} from {LANG} {IT}\.$",
        fr"Late OE\. {IT}, {IT}\.",
        fr"Modelled on {LANG} {IT}\.$",
        fr"Next \+ {LANG} {IT}\.$",
        fr"Nonce-use of {LANG} {IT}, {GLOSS}\.$",
        fr"Northern form of {CAP_WORD}, {QV}$",
        fr"Not known; only allit\.$",
        fr"Not known\.$",
        fr"Obscure; \? cf\. {LANG} {IT}, {GLOSS}\.$",
        fr"Obscure; appar\. peculiar to {CAP_WORD}\.$",
        fr"Obscure; cf\. {LANG}, {LANG} {IT}\.$",
        fr"Obscure; see {NED}, s\.v\. _{CAP_WORD}_\.$",
        fr"Obscure; usually Northern\.$",
        fr"Obscure\.$",
        fr"OE\. {IT} \({IT}, but not WS\.\)\.$",
        fr"OE\. {IT} \(Kt\. {IT}\)\.$",  # Kt inconsistency
        fr"OE\. {IT} \(late WS\. {IT}\)\.$",
        fr"OE\. {IT} \(rare\)\.$",
        fr"OE\. {IT}, \(Kt\. {IT}\)\.$",  # Kt inconsistency
        fr"OE\. {IT}, \(Kt\.\) {IT}\.$",  # Kt inconsistency
        fr"OE\. {IT}, Kt\. {IT}\.$",  # Kt inconsistency
        fr"OE\. {IT}, late Nth\. {IT}\.$",
        fr"OE\. {IT}; {GRM} {IT} \(Kt\. {IT}\)\.$",
        fr"OE\. \(late 11th c\.\) {IT}\.$",
        fr"OE\. \(late\) {IT} from {LANG} {IT}\.$",
        fr"OE\. \(late\) {IT}, {GLOSS}\.$",
        fr"OE\. \(late\) {IT}\.$",
        fr"OE\. \(Nth\.\) {IT} from {LANG} {IT}\.$",
        fr"OE\. \(Nth\.\) {IT}\.$",
        fr"OE\. \(rare Nth\.\) {IT}; {LANG} {IT}\.$",
        fr"OE\. \(WS\.\) {IT}\.$",
        fr"Origin of name doubtful; see {NED}$",
        fr"Pp\. of {CAP_WORD}.$",
        fr"Prec\. \+ _pp\._ of {CAP_WORD}\.$",
        fr"Prec\. \+ {CAP_WORD}, {QV}$",
        fr"Prec\. \+ {CAP_WORD}\.$",
        fr"Prec\. \+ {GRM} {IT}\.$",
        fr"Prec\. \+ {IT}\.$",
        fr"Prec\. \+ {LANG} {IT}, {IT}\.$",
        fr"Prec\. \+ {LANG} {IT}; {LANG} {IT}\.$",
        fr"Prec\. \+ {LANG} {IT}\.$",
        fr"Prec\. and {LANG} {IT}, border\.$",
        fr"Prob\. {LANG} {IT}, rel\. to prec\.$",
        fr"Prob\. from prec\.$",
        fr"Prob\. rel\. to {LANG} {IT}\.$",
        fr"Prob\. related to {CAP_WORD}\.$",
        fr"Prob\. same as prec\.$",
        fr"Reduced form of {CAP_WORD}, _{GRM}_$",
        fr"Reduced form of {CAP_WORD}, {QV}$",
        fr"Reduction of {CAP_WORD}{SUP}, {QV}$",
        fr"Related to {CAP_WORD} as prec\.$",
        fr"See {NED} s\.v\. {IT}\.$",
        fr"See {NED} s\.vv\. _{CAP_WORD}_, _{CAP_WORD}_\.$",
        fr"See {NED}, s\.v\. {IT} \d+\.$",  # not quite sure what the last part means
        fr"See {NED}, s\.v\. {IT}\.$",  # inconsistent comma
        fr"See {NED}$",
        fr"Shortened from {CAP_WORD}, {CAP_WORD}\.$",
        fr"Shortened from {CAP_WORD}, {QV}$",
        fr"Shortened from {CAP_WORD}\.$",
        fr"Shortened from {LANG} {IT}\.$",
        fr"Stem of {CAP_WORD} _{GRM}_ \+ {LANG} {IT}\.$",
        fr"Stem of {LANG} {IT} \+ {IT}\.",
        fr"Stem of {LANG} {IT}, {GRM}$",
        fr"Stem of {LANG} {IT}\.$",
        fr"Stem of next\.$",
        fr"Unaccented reduction of {CAP_WORD}\.$",
        fr"Unknown; _cf\._ {LANG} {IT}\.$",
        fr"Unknown\.$",
    ]
]


def check_etymology(etymology):
    for regex in regexes:
        if regex.match(etymology):
            return True
    return False
